skyline-emu/skyline

- app/src/main/AndroidManifest.xml
Android 10 and above block access to the legacy java file apis on external storage without this option. In the future the app should move to using the modern SAF apis.
> Mark as requiring legacy external storage in manifest

- app/src/main/cpp/skyline/common.h
- app/src/main/cpp/skyline/loader/loader.h
- app/src/main/cpp/skyline/loader/nro.cpp
- app/src/main/cpp/skyline/loader/nro.h
- app/src/main/cpp/skyline/os.cpp
- app/src/main/cpp/skyline/services/base_service.h
- app/src/main/cpp/skyline/services/fssrv/IFileSystemProxy.cpp
- app/src/main/cpp/skyline/services/fssrv/IFileSystemProxy.h
- app/src/main/cpp/skyline/services/fssrv/IStorage.cpp
- app/src/main/cpp/skyline/services/fssrv/IStorage.h
RomFS is used by homebrew and games to access content files, it is accessed through an IStorage object. This implementation currently only supports the `Read` and `GetSize` IStorage functions which is enough for most homebrew.
> Introduce support for RomFS

- app/CMakeLists.txt
- app/src/main/cpp/skyline/kernel/ipc.cpp
- app/src/main/cpp/skyline/kernel/ipc.h
- app/src/main/cpp/skyline/services/serviceman.cpp
1. Moves isDomain from the response itself to a parameter of `WriteResponce` to allow domain data to be ignored on control requests.
2. Adds additional checks for the -WithContext command variants - they can be treated the same as the non -WithContext versions.
> Fixes for control IPC

- app/CMakeLists.txt
- app/src/main/cpp/skyline/services/base_service.h
- app/src/main/cpp/skyline/services/serviceman.cpp
- app/src/main/cpp/skyline/services/settings/ISettingsServer.cpp
- app/src/main/cpp/skyline/services/settings/ISettingsServer.h
The 'set' service is used to obtain user settings such as language.
GetAvailableLanguageCodes is used by Puyo Puyo Tetris.
> Implement the set service together with GetAvailableLanguageCodes

- app/CMakeLists.txt
- app/src/main/cpp/skyline/services/aocsrv/IAddOnContentManager.cpp
- app/src/main/cpp/skyline/services/aocsrv/IAddOnContentManager.h
- app/src/main/cpp/skyline/services/base_service.h
- app/src/main/cpp/skyline/services/pctl/IParentalControlServiceFactory.cpp
- app/src/main/cpp/skyline/services/pctl/IParentalControlServiceFactory.h
- app/src/main/cpp/skyline/services/serviceman.cpp
These are both required by Puyo Puyo Tetris.
aoc:u will be extended in the future to allow using real DLC with the emulator.
> Add empty aoc:u and pctl implementations

- app/CMakeLists.txt
- app/src/main/cpp/skyline/services/am/storage/IStorage.cpp
- app/src/main/cpp/skyline/services/am/storage/IStorage.h
- app/src/main/cpp/skyline/services/am/storage/IStorageAccessor.cpp
- app/src/main/cpp/skyline/services/am/storage/IStorageAccessor.h
- app/src/main/cpp/skyline/services/base_service.h
In the case of am, IStorage is used to exchange buffers of data such
as application launch parameters or an applets result. It has no
relation to fsp-srv's IStorage.
This is needed for `PopLaunchParameter` however a proper implementation of that will require account services.
> Implement IStorage services in Applet Manager

- app/CMakeLists.txt
- app/src/main/cpp/skyline/services/base_service.h
- app/src/main/cpp/skyline/services/lm/ILogService.cpp
- app/src/main/cpp/skyline/services/lm/ILogService.h
- app/src/main/cpp/skyline/services/lm/ILogger.cpp
- app/src/main/cpp/skyline/services/lm/ILogger.h
- app/src/main/cpp/skyline/services/serviceman.cpp
lm is used by applications to print messages to the system log. Log
messages are made up of a header and then several fields containing
metadata or string messages.
> Implement log services (lm)

- app/src/main/cpp/skyline/services/account/IAccountServiceForApplication.h
- app/src/main/cpp/skyline/services/am/controller/IApplicationFunctions.cpp
- app/src/main/cpp/skyline/services/am/controller/IApplicationFunctions.h
PopLaunchParameters is used to obtain the user who started the application.
These are needed for Puyo Puyo Tetris.
> Extend account services and add support for PopLaunchParameters

- .idea/inspectionProfiles/Project_Default.xml
- app/CMakeLists.txt
- app/build.gradle
- app/src/main/AndroidManifest.xml
- app/src/main/cpp/skyline/audio.cpp
- app/src/main/cpp/skyline/audio.h
- app/src/main/cpp/skyline/common.cpp
- app/src/main/cpp/skyline/kernel/ipc.cpp
- app/src/main/cpp/skyline/kernel/ipc.h
- app/src/main/cpp/skyline/kernel/types/KMemory.h
- app/src/main/cpp/skyline/kernel/types/KSyncObject.h
- app/src/main/java/emu/skyline/EmulationActivity.kt
- app/src/main/java/emu/skyline/loader/RomFile.kt
- build.gradle
- Updates the Kotlin code to support the Android R SDK
- Switches the build SDK to Android R
- Enables `-Wall` and fixes the associated warnings
- The warnings for reordering are left disabled as they are rather pedantic
> Updates for the Android R SDK and C++ fixes

- app/CMakeLists.txt
- app/src/main/cpp/skyline/audio/adpcm_decoder.cpp
- app/src/main/cpp/skyline/audio/adpcm_decoder.h
- app/src/main/cpp/skyline/services/audio/IAudioRenderer/voice.cpp
- app/src/main/cpp/skyline/services/audio/IAudioRenderer/voice.h
This is used by many retail games, it only supports mono sound.
This implementation is based on Ryu's.
> Implement an ADPCM decoder for audren

- app/CMakeLists.txt
- app/src/main/cpp/skyline/services/am/applet/ILibraryAppletAccessor.cpp
- app/src/main/cpp/skyline/services/am/applet/ILibraryAppletAccessor.h
- app/src/main/cpp/skyline/services/am/controller/ILibraryAppletCreator.cpp
- app/src/main/cpp/skyline/services/am/controller/ILibraryAppletCreator.h
- app/src/main/cpp/skyline/services/am/controller/ISelfController.cpp
- app/src/main/cpp/skyline/services/am/controller/ISelfController.h
- app/src/main/cpp/skyline/services/am/storage/IStorageAccessor.cpp
- app/src/main/cpp/skyline/services/am/storage/IStorageAccessor.h
- app/src/main/cpp/skyline/services/base_service.h
This commit adds stubs for the library applet and adds support for
writing to an AM IStorage.
It will be replaced by a somewhat more proper applet implementation in the distant future.
> Extend applet manager services for the library applet

- app/src/main/cpp/skyline/services/audio/IAudioOut.cpp
- app/src/main/cpp/skyline/services/audio/IAudioOutManager.cpp
- app/src/main/cpp/skyline/services/audio/IAudioRenderer/IAudioRenderer.cpp
* Those are needed to run playtone and audren from switch homebrew examples
> services: Add missing audio functions

- app/CMakeLists.txt
- app/src/main/cpp/skyline/gpu.h
- app/src/main/cpp/skyline/gpu/memory_manager.cpp
- app/src/main/cpp/skyline/gpu/memory_manager.h
- app/src/main/cpp/skyline/services/nvdrv/INvDrvServices.cpp
- app/src/main/cpp/skyline/services/nvdrv/devices/nvhost_as_gpu.cpp
- app/src/main/cpp/skyline/services/nvdrv/devices/nvhost_as_gpu.h
- app/src/main/cpp/skyline/services/nvdrv/devices/nvhost_channel.cpp
- app/src/main/cpp/skyline/services/nvdrv/devices/nvhost_channel.h
- app/src/main/cpp/skyline/services/nvdrv/devices/nvhost_ctrl.cpp
- app/src/main/cpp/skyline/services/nvdrv/devices/nvhost_ctrl.h
- app/src/main/cpp/skyline/services/nvdrv/devices/nvhost_ctrl_gpu.cpp
- app/src/main/cpp/skyline/services/nvdrv/devices/nvmap.cpp
The GPU has it's own seperate address space to the CPU. It is able to
address 40 bit addresses and accesses the system memory. A sorted vector
has been used to store blocks as insertions are not very frequent.
> Implement a block based GPU virtual memory manager

- app/CMakeLists.txt
- app/src/main/cpp/emu_jni.cpp
- app/src/main/cpp/skyline/common.cpp
- app/src/main/cpp/skyline/common.h
- app/src/main/cpp/skyline/os.cpp
- app/src/main/cpp/skyline/os.h
- app/src/main/cpp/skyline/services/base_service.h
- app/src/main/cpp/skyline/services/fssrv/IFile.cpp
- app/src/main/cpp/skyline/services/fssrv/IFile.h
- app/src/main/cpp/skyline/services/fssrv/IFileSystem.cpp
- app/src/main/cpp/skyline/services/fssrv/IFileSystem.h
- app/src/main/cpp/skyline/services/fssrv/IFileSystemProxy.cpp
- app/src/main/cpp/skyline/services/fssrv/IFileSystemProxy.h
- app/src/main/cpp/skyline/services/fssrv/IStorage.cpp
- app/src/main/cpp/skyline/vfs/backing.h
- app/src/main/cpp/skyline/vfs/filesystem.h
- app/src/main/cpp/skyline/vfs/nacp.h
- app/src/main/cpp/skyline/vfs/os_backing.cpp
- app/src/main/cpp/skyline/vfs/os_backing.h
- app/src/main/cpp/skyline/vfs/os_filesystem.cpp
- app/src/main/cpp/skyline/vfs/os_filesystem.h
- app/src/main/cpp/skyline/vfs/partition_filesystem.cpp
- app/src/main/cpp/skyline/vfs/partition_filesystem.h
- app/src/main/cpp/skyline/vfs/rom_filesystem.cpp
- app/src/main/cpp/skyline/vfs/rom_filesystem.h
- app/src/main/java/emu/skyline/EmulationActivity.kt
- app/src/main/java/emu/skyline/LogActivity.kt
- app/src/main/java/emu/skyline/MainActivity.kt
This PR implements basic savedata creation using the newly introduced OsFileSystem API. The savedata is stored within skyline's 'files' directory in the same format as yuzu. This also implements very basic support for sdcard accesses with the filesystem API.
In the future Skyline will provide a storage provider interface that can be used to transfer savedata.
> Initial Savedata Implementation

- app/CMakeLists.txt
- app/src/main/cpp/emu_jni.cpp
- app/src/main/cpp/skyline/common.h
- app/src/main/cpp/skyline/gpu/gpfifo.h
- app/src/main/cpp/skyline/gpu/memory_manager.h
- app/src/main/cpp/skyline/input/npad.cpp
- app/src/main/cpp/skyline/input/npad.h
- app/src/main/cpp/skyline/input/npad_device.cpp
- app/src/main/cpp/skyline/input/npad_device.h
- app/src/main/cpp/skyline/input/sections/Npad.h
- app/src/main/cpp/skyline/jvm.cpp
- app/src/main/cpp/skyline/jvm.h
- app/src/main/cpp/skyline/nce.cpp
- app/src/main/cpp/skyline/services/account/IAccountServiceForApplication.cpp
- app/src/main/cpp/skyline/services/base_service.h
- app/src/main/cpp/skyline/services/hid/IActiveVibrationDeviceList.cpp
- app/src/main/cpp/skyline/services/hid/IActiveVibrationDeviceList.h
- app/src/main/cpp/skyline/services/hid/IHidServer.cpp
- app/src/main/cpp/skyline/services/hid/IHidServer.h
- app/src/main/cpp/skyline/services/nvdrv/devices/nvhost_channel.cpp
- app/src/main/java/emu/skyline/EmulationActivity.kt
- app/src/main/java/emu/skyline/adapter/ControllerAdapter.kt
- app/src/main/java/emu/skyline/input/Controller.kt
- app/src/main/java/emu/skyline/input/dialog/RumbleDialog.kt
- app/src/main/res/layout/rumble_dialog.xml
- app/src/main/res/values/strings.xml
- build.gradle
This PR adds in a translation layer for all guest vibration to be converted into corresponding host vibration data and ran on host vibrators using Android Vibration APIs. There's support for using vibrators present in the controllers and those which are present in the device itself.
> Implement Vibration Emulation for Host Vibrators

- app/src/main/cpp/skyline/vfs/backing.h
An incorrect check introduced in #135 has broken all VFS backing reads, this PR corrects that check.
> Fix backing read size check

- app/src/main/java/emu/skyline/KeyReader.kt
I wanted to try skyline and it kept rejecting my prod.keys file. Turned out to be caused by an empty line.
> Ignore empty lines in key files

- app/src/main/cpp/skyline/services/account/IAccountServiceForApplication.cpp
- app/src/main/cpp/skyline/services/account/IAccountServiceForApplication.h
This PR stubs some functions in [IAccountServiceForApplication](https://switchbrew.org/wiki/Account_services#acc:u0) :
- IAccountServiceForApplication::GetUserCount (0x0)
- IAccountServiceForApplication::InitializeApplicationInfo (0x8C)
- IAccountServiceForApplication::IsUserAccountSwitchLocked (0x96)
This is required by New Pokémon Snap, implementing these services makes this game boot a bit further and display a (broken) splash screen.
> Implement some IAccountServiceForApplication functions

- app/src/main/java/emu/skyline/KeyReader.kt
- app/src/main/java/emu/skyline/MainActivity.kt
- app/src/main/java/emu/skyline/MainViewModel.kt
`title.keys` and `prod.keys` files found in the search location folder are now imported automatically (subfolders included). This means it should no longer be necessary to manually import keys if they are kept in the same folder as games.
> Automatically import key files from search location

- app/src/main/cpp/skyline/services/am/controller/ICommonStateGetter.cpp
- app/src/main/cpp/skyline/services/am/controller/ICommonStateGetter.h
This makes Metroid Dread boot, although it has very major graphical glitches. (Screenshot is from the game's gallery)
> Stub ICommonStateGetter::SetCpuBoostMode

- app/src/main/java/emu/skyline/EmulationActivity.kt
- app/src/main/java/emu/skyline/input/onscreen/OnScreenEditActivity.kt
- app/src/main/java/emu/skyline/utils/Settings.kt
- app/src/main/res/layout/emu_activity.xml
- app/src/main/res/values/dimens.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/preferences.xml
* The game view now extends from edge to edge of the screen when stretched, and is properly centered when 16:9
* Added a setting to force respecting display cutouts for on-screen elements (FPS counter, OSC toggle), forcing margin to be applied to those elements to render outside of the cutout area. Most users will not need this, but it might be necessary for some devices that have the camera pinhole on the top right of the screen.
> Add support for drawing inside the display cutout areas

- .github/workflows/ci.yml
- .gitmodules
- app/CMakeLists.txt
- app/build.gradle
Using [boostorg/boost](https://github.com/boostorg/boost) slowed down GitKraken and git-cmd to unusable levels because of the amount of recursive submodules that repository has. We have decided to solve this issue by making a fork of that repo, [skyline-emu/boost](https://github.com/skyline-emu/boost), tailored down to only the submodules we use in Skyline's codebase, cloned with depth 1 (shallow). This speeds up `git` operations significantly across the repository.
Note: if you have used the repository prior to this point, after this PR is merged you'll need to reset the boost submodule and clean CMake and Gradle cache:
```sh
cd app/libraries
git submodule sync boost
cd boost
git remote -vv
git checkout origin/HEAD
git submodule deinit
cd ..
git submodule update --init --recursive boost …
```
> Swap out boostorg/boost for skyline-emu/boost

- app/src/main/cpp/skyline/services/am/controller/IApplicationFunctions.h
According to [SwitchBrew](https://switchbrew.org/wiki/Applet_Manager_services#IApplicationFunctions), it should be 0x17 and not 0x16
> Fix IApplicationFunctions::GetDisplayVersion id

- app/src/main/cpp/skyline/common/language.h
The American English language code wasn't correctly capitalized, which led to bugs in some games like Metroid Dread when American English or British English was selected.
Without the fix:
With the fix:
> Fix American English language code.

- app/src/main/cpp/skyline/common/span.h
- app/src/main/cpp/skyline/gpu/buffer.cpp
- app/src/main/cpp/skyline/gpu/texture/texture.cpp
- app/src/main/cpp/skyline/input.h
- app/src/main/cpp/skyline/kernel/memory.cpp
- app/src/main/cpp/skyline/kernel/memory.h
- app/src/main/cpp/skyline/kernel/svc.cpp
- app/src/main/cpp/skyline/kernel/types/KMemory.h
- app/src/main/cpp/skyline/kernel/types/KPrivateMemory.cpp
- app/src/main/cpp/skyline/kernel/types/KPrivateMemory.h
- app/src/main/cpp/skyline/kernel/types/KProcess.cpp
- app/src/main/cpp/skyline/kernel/types/KSharedMemory.cpp
- app/src/main/cpp/skyline/kernel/types/KSharedMemory.h
- app/src/main/cpp/skyline/kernel/types/KTransferMemory.h
- app/src/main/cpp/skyline/loader/loader.cpp
- app/src/main/cpp/skyline/loader/nca.cpp
- app/src/main/cpp/skyline/loader/nro.cpp
- app/src/main/cpp/skyline/loader/nso.cpp
- app/src/main/cpp/skyline/nce.cpp
- app/src/main/cpp/skyline/services/am/storage/TransferMemoryIStorage.cpp
- app/src/main/cpp/skyline/services/codec/IHardwareOpusDecoder.cpp
- app/src/main/cpp/skyline/services/pl/shared_font_core.h
- app/src/main/cpp/skyline/services/timesrv/time_shared_memory.cpp
This makes the code more readable and allowed removing a bunch of one-liner functions
> Use spans instead of ptr and size in kernel memory

- app/CMakeLists.txt
- app/src/main/cpp/skyline/applet/applet_creator.cpp
- app/src/main/cpp/skyline/applet/controller_applet.cpp
- app/src/main/cpp/skyline/applet/controller_applet.h
- app/src/main/cpp/skyline/applet/error_applet.cpp
- app/src/main/cpp/skyline/applet/error_applet.h
- app/src/main/cpp/skyline/applet/player_select_applet.cpp
- app/src/main/cpp/skyline/applet/swkbd/software_keyboard_applet.cpp
- app/src/main/cpp/skyline/applet/swkbd/software_keyboard_applet.h
- app/src/main/cpp/skyline/applet/swkbd/software_keyboard_config.cpp
- app/src/main/cpp/skyline/services/am/applet/IApplet.h
These applets are used by applications to display a custom error message to the user. Both the error message and the detailed error message are printed to the error log. (thx @lynxnb)
> Write `ApplicationErrorArg` `ErrorApplet`s to log

- app/src/main/cpp/skyline/services/codec/IHardwareOpusDecoder.cpp
- app/src/main/cpp/skyline/services/codec/IHardwareOpusDecoder.h
- app/src/main/cpp/skyline/services/codec/IHardwareOpusDecoderManager.cpp
- app/src/main/cpp/skyline/services/codec/IHardwareOpusDecoderManager.h
Implements these 2 functions which were introduced in HOS 12.0.0. Fixes a crash in Xenoblade Chronicles 3.
> Implement OpenHardwareOpusDecoderEx and GetWorkBufferSizeEx

- app/src/main/cpp/skyline/services/socket/bsd/IClient.cpp
- app/src/main/cpp/skyline/services/socket/bsd/IClient.h
These changes allow Dark Souls (maybe some other games) go to in game with save file (without save file it crashes on inline swkbd) on ftx1, didn't try with gpu-new.
P.S. I don't know what to write in @brief of GetIndirectLayerImageRequiredMemoryInfo. And I'm not cpp dev, so I'm sorry if I did something wrong.
> stub IClient::Poll and implement IApplicationDisplayService::GetIndirectLayerImageRequiredMemoryInfo

- app/src/main/cpp/skyline/services/settings/ISettingsServer.cpp
- app/src/main/cpp/skyline/services/settings/ISettingsServer.h
fixes `Data being copied is larger than this span` in some games like Tales of Vesperia, V-Rally 4 and etc.
> add GetAvailableLanguageCodeCount for both language code lists

- app/src/main/cpp/skyline/input/npad_device.cpp
- app/src/main/cpp/skyline/input/npad_device.h
- app/src/main/cpp/skyline/input/touch.cpp
- app/src/main/cpp/skyline/services/hid/IHidServer.cpp
- app/src/main/cpp/skyline/services/hid/IHidServer.h
This PR should fix random input in some games like Pokemon Sword. Random disconnects on games like Flip Wars.
- Stubs SetPalmaBoostMode
- Signal the update event on AcquireNpadStyleSetUpdateEventHandle
- Initialize and reset shared memory properly instead of fully deleting the contents
> service: hid: Improve npad device detection

- app/src/main/cpp/skyline/services/fssrv/IFileSystemProxy.cpp
- app/src/main/cpp/skyline/services/fssrv/IFileSystemProxy.h
Forward this function to OpenSaveDataFileSystem for now. A proper implementation should wrap the underlying filesystem with nn::fs::ReadOnlyFileSystem.
> fssrv: IFileSystemProxy: Implement OpenReadOnlySaveDataFileSystem

- app/src/main/cpp/skyline/kernel/memory.cpp
- app/src/main/cpp/skyline/kernel/memory.h
- app/src/main/cpp/skyline/kernel/svc.cpp
- app/src/main/cpp/skyline/kernel/types/KPrivateMemory.cpp
- app/src/main/cpp/skyline/kernel/types/KPrivateMemory.h
- app/src/main/cpp/skyline/kernel/types/KProcess.cpp
- app/src/main/cpp/skyline/kernel/types/KProcess.h
- app/src/main/cpp/skyline/kernel/types/KSharedMemory.cpp
This is quite a horrible solution but fixing it properly would require a whole rewrite of how we handle memory. Vastly reduces stutters in skyrim from searching over thousands of handles every unmap.
> Store KMemory object ptrs in memory class to avoid linear-time unmap

- app/src/main/java/emu/skyline/EmulationActivity.kt
- app/src/main/java/emu/skyline/input/onscreen/OnScreenEditActivity.kt
Some older android roms may have broken immersive mode implementation that causes navigation bar to stick out indefinitely after touching the screen.
This workaround should fix it.
> navbar sticking out workaround for certain android roms

- app/src/main/cpp/skyline/services/account/IAccountServiceForApplication.cpp
- app/src/main/cpp/skyline/services/account/IAccountServiceForApplication.h
- app/src/main/cpp/skyline/services/account/IManagerForApplication.cpp
- app/src/main/cpp/skyline/services/account/IManagerForApplication.h
- app/src/main/cpp/skyline/services/am/controller/IApplicationFunctions.cpp
- app/src/main/cpp/skyline/services/am/controller/IApplicationFunctions.h
- app/src/main/cpp/skyline/services/am/controller/ISelfController.cpp
- app/src/main/cpp/skyline/services/am/controller/ISelfController.h
- app/src/main/cpp/skyline/services/aocsrv/IAddOnContentManager.cpp
- app/src/main/cpp/skyline/services/aocsrv/IAddOnContentManager.h
- app/src/main/cpp/skyline/services/friends/IFriendService.cpp
- app/src/main/cpp/skyline/services/friends/IFriendService.h
- app/src/main/cpp/skyline/services/nim/IShopServiceAccessServerInterface.cpp
- app/src/main/cpp/skyline/services/nim/IShopServiceAccessServerInterface.h
- app/src/main/cpp/skyline/services/pctl/IParentalControlService.cpp
- app/src/main/cpp/skyline/services/pctl/IParentalControlService.h
Since there is no friend future, TryPopFromFriendInvitationStorageChannel can return `result::NotAvailable`.
`GetAddOnContentListChangedEventWithProcessId` should allow BLUE REFLECTION: Second Light go ingame and also needed for  Tony Hawk's™ Pro Skater™ 1 + 2, Harvestella and some other games. Other funcs also needed for some games.
> Stub some functions

- app/src/main/cpp/skyline/common/utils.h
- app/src/main/cpp/skyline/nce.cpp
- app/src/main/cpp/skyline/nce/guest.S
- app/src/main/cpp/skyline/nce/guest.h
Exynos SoCs have a bug where the `CNTFRQ_EL0` register is either set to 0 or contain incoherent values. With this patch, the frequency value is loaded into a static variable and used instead of reading the register. The value will be initialised to the correct value for affected SoCs, while unaffected ones will use the value from the register.
> Work around invalid values in `CNTFRQ_EL0` register

- app/src/main/cpp/skyline/kernel/memory.cpp
- app/src/main/cpp/skyline/kernel/memory.h
- app/src/main/cpp/skyline/kernel/types/KPrivateMemory.cpp
- app/src/main/cpp/skyline/kernel/types/KSharedMemory.cpp
- app/src/main/cpp/skyline/loader/loader.cpp
Although rtld and IPC prevent TLS/IO and code from being above the 36-bit AS limit, nothing depends the heap being below it. We can take advantage of this by stealing as much AS as possible for code in the lower 36-bits.
> Implement support for 36 bit games by using split code/heap mappings

- app/src/main/java/emu/skyline/EmulationActivity.kt
- app/src/main/java/emu/skyline/input/ControllerActivity.kt
- app/src/main/java/emu/skyline/input/onscreen/OnScreenButton.kt
- app/src/main/java/emu/skyline/input/onscreen/OnScreenControllerView.kt
- app/src/main/java/emu/skyline/utils/PreferenceSettings.kt
- app/src/main/res/values/strings.xml
No frills vibration for OSC buttons. Toggled from input settings, only activates for OSC, doesn't apply to joysticks. Vibration length / intensity mirrors pressing one of the navigation buttons (home, back, etc). Fulfills #2009
> Add a rudimentary OSC button vibration setting

- app/src/main/cpp/skyline/input/npad_device.cpp
- app/src/main/cpp/skyline/input/npad_device.h
- app/src/main/cpp/skyline/services/hid/IHidServer.cpp
- app/src/main/cpp/skyline/services/hid/IHidServer.h
Related service calls are called in a loop by SM3DW. A variable tracking zero drift mode has been added to `npad_device`, but it's unused at the moment.
> Stub `GyroscopeZeroDriftMode`

- app/src/main/cpp/skyline/gpu/texture/texture.cpp
Fixes a small typo with comically large consequences. Fixes textures randomly turning black in Pokemon Let's go games and most likely a lot of other games as well.
TLDR: It was copying from the destination to the source before.
> Fix small typo

- app/src/main/cpp/skyline/gpu/trait_manager.cpp
- app/src/main/cpp/skyline/gpu/trait_manager.h
`VK_KHR_image_format_list` is a requirement for `VK_KHR_imageless_framebuffer`, which we use.
> Enable `VK_KHR_image_format_list` during device init

- app/src/main/cpp/skyline/common/utils.h
> Add `CNTFRQ_EL0` workaround value for Exynos 1280

- app/src/main/java/emu/skyline/MainActivity.kt
- app/src/main/java/emu/skyline/preference/ChkBoxPreference.kt
- app/src/main/java/emu/skyline/preference/RefreshCheckBoxPreference.kt
- app/src/main/java/emu/skyline/utils/PreferenceSettings.kt
- app/src/main/res/values/array.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/preferences.xml
Functionality is added to the game list on the main screen, adding and option to disable grouping the games by format, and adding an additional option to sort games by alphabetical order, from A-Z or Z-A at the moment, thinking of adding options for sorting by favorites, and played count.
> Add options to group and sort games

- app/src/main/cpp/skyline/kernel/svc.cpp
Certain titles such as Super Smash Bros Ultimate can use SVC `UnmapPhysicalMemory` to punch holes into physical memory mappings, this wasn't handled correctly as we completely deleted the portion after the hole. It has now been fixed which results in these titles which depend on this behavior to work now. 
Thanks to @dima-xd for investigating this issue.
**SSBU booting**
> Fix hole punching in mappings with SVC `UnmapPhysicalMemory`

- app/src/main/cpp/skyline/gpu/interconnect/maxwell_3d/pipeline_state.cpp
- app/src/main/cpp/skyline/gpu/interconnect/maxwell_3d/pipeline_state.h
- app/src/main/cpp/skyline/gpu/texture/layout.cpp
A large amount of titles suffered from having corrupted textures (such as on Nier Automata) or arbitrary crashes (such as on SMO) due to OOB access to textures during deswizzling due to various reasons, this PR aims to fix those broken textures and significantly improve stability across the board.
**Note:** This does not fix all broken textures as they may be broken due to the current `TextureManager` implementation being incomplete.
**No more pink textures on Nier: Automata**
> Fix out-of-bound access to textures during deswizzling

- app/src/main/cpp/skyline/gpu/interconnect/common/textures.cpp
- app/src/main/cpp/skyline/gpu/texture/format.h
Cult of the Lamb must be in-game (Requires save and version 1.0.5) and should fix some textures in Bayonetta 3 
Closes #2170
> Add TIC format: 0x58D24946

- app/src/main/AndroidManifest.xml
- app/src/main/java/emu/skyline/EmulationActivity.kt
- app/src/main/java/emu/skyline/MainActivity.kt
- app/src/main/java/emu/skyline/SettingsActivity.kt
- app/src/main/java/emu/skyline/input/ControllerActivity.kt
Not a strictly necessary change at the the moment, but Android is removing support for the `onBackPressed` callback to implement perhaps one of their sillier design changes where you can preview where you are going back to before inevitably going back there regardless. 
The way it's explained and the way it functions are the difference between seeing an artist rendering of a new console and then seeing the release product. Ironically, this is the change required for API 13+ and then the actual change to make the new transitions work is a separate condition for API 33 + (that is not currently included in this PR). It almost makes this seem pointless, but I guess it keeps it from colliding with the new handling.
> `onBackPressed` -> `onBackPressedDispatcher`

- app/src/main/cpp/skyline/services/hosbinder/IHOSBinderDriver.cpp
This allows Portal 1 and 2 to boot and go in game. Instead of replacing the previous layer when a new one is created, we just ignore the new ones, until proper multiple layers support is implemented.
I don't have any other game with multiple layer creations so I can't test if there are regression in other games with this change. If so, please feel free to close this pull request.
Video of Portal 2 in game
https://user-images.githubusercontent.com/10391562/216836835-7dc5a647-cbed-4d2f-a346-ae0526d7f7ae.mp4
Images of Portal 1 in game (credits to Cudzlox on Discord)
> Ignore new layer creations instead of replacing previous ones

- app/src/main/cpp/emu_jni.cpp
- app/src/main/cpp/skyline/common/android_settings.h
- app/src/main/cpp/skyline/gpu/presentation_engine.cpp
- app/src/main/cpp/skyline/gpu/presentation_engine.h
- app/src/main/cpp/skyline/jvm.h
- app/src/main/java/emu/skyline/EmulationActivity.kt
I made a suggestion few days ago about adding a toggle button for enabling/disabling frame throttling.
At first I thought about adding special button but it was easier to do it by clicking on FPS counter.
Not sure if I did it right, it was not working until I updated the setting inside presentation engine and updated the swapchain.
Tested on my phone and it seems to be working.
> Toggle DisableFrameThrottling setting by clicking on FPS display

- app/src/main/res/layout/header_rom_filter.xml
This is aimed at tablets and users with a modified density. With "Minimum width" being part of Developer options and the adb `wm` command being available without root, this targets a much larger audience. Wrapping the ChipGroup in a ConstraintLayout allows centering it non-destructively for those with a previously large right margin. For anyone that couldn't fit them all before, everything should look the same as always.
> Align ChipGroup to center when space exists

- app/src/main/java/emu/skyline/preference/ProfilePicturePreference.kt
This solves the entire image path being listed, which is excess information because the app's public files path is standardized across all Android apps. While the app needs that information to load the image, it makes for a really long summary.
> Resolve the awkwardness of photo preview

- app/src/main/cpp/skyline/gpu/interconnect/inline2memory.cpp
- app/src/main/cpp/skyline/gpu/interconnect/inline2memory.h
- app/src/main/cpp/skyline/gpu/interconnect/maxwell_dma.cpp
- app/src/main/cpp/skyline/gpu/interconnect/maxwell_dma.h
- app/src/main/cpp/skyline/gpu/texture/layout.cpp
- app/src/main/cpp/skyline/gpu/texture/layout.h
- app/src/main/cpp/skyline/soc/gm20b/engines/inline2memory.cpp
- app/src/main/cpp/skyline/soc/gm20b/engines/inline2memory.h
- app/src/main/cpp/skyline/soc/gm20b/engines/maxwell_dma.cpp
- app/src/main/cpp/skyline/soc/gm20b/engines/maxwell_dma.h
In more detail the following was implemented: Support for pitch copies in the DMA engine (including pitch to pitch), Subrect copies, 3D copy support. and small optimizations to the base copy function. 
These changes were largely untested due to me lacking games that use these features, but I am confident that this code has no issues, however they should be tested either way before being merged.
Edit: The pull request now also includes support for all I2M copy functionality
Closes #1108
> Implement various DMA engine features and copy methods

- app/src/main/java/emu/skyline/AppDialog.kt
- app/src/main/java/emu/skyline/EmulationActivity.kt
- app/src/main/java/emu/skyline/preference/GpuDriverActivity.kt
- app/src/main/java/emu/skyline/settings/GameSettingsFragment.kt
- app/src/main/java/emu/skyline/utils/SerializationHelper.kt
Split this out from #2199 because of the merge conflict it would have with #2246 since it has nothing to do with picture in picture and is easier to fix alone.
> Support  deprecation of `getSerializableExtra`

- app/src/main/AndroidManifest.xml
- app/src/main/java/emu/skyline/EmulationActivity.kt
- app/src/main/res/drawable/ic_pause.xml
- app/src/main/res/drawable/ic_volume_mute.xml
- app/src/main/res/layout/emu_activity.xml
- app/src/main/res/values/strings.xml
When you launch a game and hit the home or recents button, the emulation activity does picture-in-picture similar to the YouTube app. This one is good for when you have to send a text or something else you need to launch from the home screen and want to make sure the game isn't killed off in the background. The onscreen controls are currently hidden in PiP mode and restored when returning.
It can be completely disabled by either going into PiP and pressing the gear, which opens the PiP settings or (on Samsung and potentially on most Android devices) by opening the Settings app and going to Apps -> Overflow menu (3 dots, top right) -> Special access -> Picture-in-picture.
Not sure if this is something desirable, but I had fun with it.
<details>
<summary>Screenshot</summary>
</details>
> Add picture in picture for emulation activity

- app/build.gradle
I kept wondering why the Java version was identical and still complaining they were not set to the same value on half of my projects. This seems to avoid the warning, which isn't consistent.
Also addressed the CI warning "PackagingOptions.jniLibs.useLegacyPackaging should be set to true because android:extractNativeLibs is set to "true" in AndroidManifest.xml"
> Suppress a linear configuration warning

- app/src/main/java/emu/skyline/settings/GameSettingsFragment.kt
- app/src/main/java/emu/skyline/settings/SettingsActivity.kt
- app/src/main/res/menu/settings_menu.xml
Both categories and preferences are searchable, and queries can be concatenated with `,`.
> Add search to settings

- app/src/main/java/emu/skyline/EmulationActivity.kt
- app/src/main/java/emu/skyline/input/Controller.kt
- app/src/main/java/emu/skyline/input/GuestEvent.kt
- app/src/main/java/emu/skyline/input/InputHandler.kt
- app/src/main/java/emu/skyline/input/onscreen/OnScreenButton.kt
- app/src/main/java/emu/skyline/input/onscreen/OnScreenConfiguration.kt
- app/src/main/java/emu/skyline/input/onscreen/OnScreenControllerView.kt
- app/src/main/java/emu/skyline/input/onscreen/OnScreenEditActivity.kt
- app/src/main/java/emu/skyline/input/onscreen/OnScreenEditInfo.kt
- app/src/main/java/emu/skyline/input/onscreen/OnScreenItemDefinitions.kt
- app/src/main/java/emu/skyline/settings/AppSettings.kt
- app/src/main/java/emu/skyline/views/AlignmentGridView.kt
- app/src/main/res/drawable/ic_grid_off.xml
- app/src/main/res/drawable/ic_grid_on.xml
- app/src/main/res/drawable/ic_move.xml
- app/src/main/res/drawable/ic_resize.xml
- app/src/main/res/layout/on_screen_edit_activity.xml
- app/src/main/res/values/strings.xml
Some long standing issues in on-screen controls have been fixed in this first wave of improvements, with more to come in following PRs.
- Buttons can be aligned to grid
- Button size can be adjusted invididually
- Better default position (you might need to reset buttons to default to see it)
- Separate L3/R3 buttons, disabled by default
- Toned down haptic feedback (vibration) a bit
See individual commits for details.
> On-Screen Controls Improvements Part 1

- app/src/main/cpp/skyline/services/pl/IPlatformServiceManager.cpp
Not sure why, but Ryujinx returns size of loaded fonts and size of all fonts (https://github.com/Ryujinx/Ryujinx/blob/08831eecf77cedd3c4192ebab5a9c485fb15d51e/Ryujinx.HLE/HOS/Services/Sdb/Pl/ISharedFontManager.cs#L100). While Yuzu and Skyline returns loaded state and size of loaded fonts (https://github.com/yuzu-emu/yuzu/blob/54c359d1e3915653ce07a26e0e574aca5a331cb1/src/core/hle/service/ns/iplatform_service_manager.cpp#L292).
Changing to what returns Ryujinx fixes Kirby games, Tsukihime (maybe some others)
> Fix GetSharedFontInOrderOfPriority

- app/src/main/java/emu/skyline/EmulationActivity.kt
- app/src/main/java/emu/skyline/adapter/AppViewItem.kt
- app/src/main/java/emu/skyline/adapter/GpuDriverViewItem.kt
- app/src/main/java/emu/skyline/applet/swkbd/SoftwareKeyboardConfig.kt
- app/src/main/java/emu/skyline/applet/swkbd/SoftwareKeyboardDialog.kt
- app/src/main/java/emu/skyline/preference/DocumentsProviderPreference.kt
- app/src/main/java/emu/skyline/utils/ByteBufferSerializable.kt
- app/src/main/java/emu/skyline/utils/ParcelableHelper.kt
- app/src/main/java/emu/skyline/utils/WindowInsetsHelper.kt
Pause can happen in a few ways and some may not retain a flag that the emulator was paused, which can result in resume not being fired. What little is saved by not changing settings that are already set would be lost trying to effectively track the specific method the emulator was paused.
> Crash fixes for uncommon occurences 
