README.md
* Cleaned up everything, as well as making everything correct
=> Revised Readme

app/build.gradle, app/src/main/java/emu/skyline/LogActivity.kt, app/src/main/java/emu/skyline/MainActivity.kt, app/src/main/java/emu/skyline/utility/GameDialog.kt, build.gradle, gradle/wrapper/gradle-wrapper.properties
Picked some low hanging fruit here. Commits are atomic so if something is not wanted, let me know and I'll drop them.
=> Some small refactoring for the app

README.md
Also refer to the right file, 404's on master atm
=> Change licenses in readme

.gitmodules, .idea/vcs.xml, app/CMakeLists.txt, app/src/main/cpp/loader_jni.cpp, app/src/main/cpp/skyline/kernel/memory.h, app/src/main/cpp/skyline/loader/executable.h, app/src/main/cpp/skyline/loader/loader.cpp, app/src/main/cpp/skyline/loader/loader.h, app/src/main/cpp/skyline/loader/nro.cpp, app/src/main/cpp/skyline/loader/nro.h, app/src/main/cpp/skyline/loader/nso.cpp, app/src/main/cpp/skyline/loader/nso.h, app/src/main/cpp/skyline/os.cpp, app/src/main/java/emu/skyline/MainActivity.kt, app/src/main/java/emu/skyline/loader/RomFile.kt
This reworks the executable loading code to be common between loaders and implements an NSO loader.
Huge thanks to cohaereo for the initial implementation.
=> Implement an NSO loader 

app/src/main/cpp/skyline/audio/track.cpp, app/src/main/cpp/skyline/kernel/ipc.cpp, app/src/main/cpp/skyline/kernel/ipc.h, app/src/main/cpp/skyline/kernel/memory.cpp, app/src/main/cpp/skyline/kernel/memory.h, app/src/main/cpp/skyline/kernel/svc.cpp, app/src/main/cpp/skyline/kernel/types/KPrivateMemory.cpp, app/src/main/cpp/skyline/kernel/types/KProcess.cpp, app/src/main/cpp/skyline/kernel/types/KSharedMemory.cpp, app/src/main/cpp/skyline/kernel/types/KSharedMemory.h, app/src/main/cpp/skyline/loader/loader.cpp, app/src/main/cpp/skyline/os.cpp, app/src/main/cpp/skyline/services/audio/IAudioRenderer/IAudioRenderer.cpp, app/src/main/cpp/skyline/services/audio/IAudioRenderer/IAudioRenderer.h, app/src/main/cpp/skyline/services/base_service.h, app/src/main/cpp/skyline/services/hosbinder/IHOSBinderDriver.cpp, app/src/main/cpp/skyline/services/serviceman.cpp, app/src/main/cpp/skyline/services/visrv/IApplicationDisplayService.cpp
We need to do further testing of this in homebrew to ensure nothing has regressions.
=> Various bugfixes to fix inaccuracies in the emulator

app/src/main/res/layout/main_activity.xml
=> MainActivity: Fix shadows of FABs

app/src/main/java/emu/skyline/AppDialog.kt, app/src/main/java/emu/skyline/MainActivity.kt, app/src/main/java/emu/skyline/adapter/AppAdapter.kt, app/src/main/java/emu/skyline/adapter/HeaderAdapter.kt, app/src/main/java/emu/skyline/adapter/LogAdapter.kt, app/src/main/java/emu/skyline/data/AppItem.kt, app/src/main/java/emu/skyline/data/BaseItem.kt, app/src/main/java/emu/skyline/loader/RomFile.kt, app/src/main/res/drawable/background_gradient.xml, app/src/main/res/layout/app_item_grid_compact.xml, app/src/main/res/layout/app_item_linear.xml, app/src/main/res/values/array.xml, app/src/main/res/values/dimens.xml
* Refactor some classes and clean up
* Refresh style on the fly
=> Redesign cards in grid view

app/CMakeLists.txt, app/src/main/cpp/emu_jni.cpp, app/src/main/cpp/skyline/common.h, app/src/main/cpp/skyline/input.cpp, app/src/main/cpp/skyline/input.h, app/src/main/cpp/skyline/input/sections/TouchScreen.h, app/src/main/cpp/skyline/input/touch.cpp, app/src/main/cpp/skyline/input/touch.h, app/src/main/java/emu/skyline/EmulationActivity.kt
This PR implements a translation layer from the host Android Touch APIs into HOS Touch which is done through HID Shared Memory.
=> Implement Guest Touch-Screen Support

app/CMakeLists.txt, app/src/main/cpp/skyline/gpu/memory_manager.cpp, app/src/main/cpp/skyline/gpu/memory_manager.h, app/src/main/cpp/skyline/services/account/IManagerForApplication.cpp, app/src/main/cpp/skyline/services/account/IManagerForApplication.h, app/src/main/cpp/skyline/services/am/storage/IStorageAccessor.cpp, app/src/main/cpp/skyline/services/fssrv/IDirectory.cpp, app/src/main/cpp/skyline/services/fssrv/IDirectory.h, app/src/main/cpp/skyline/services/fssrv/IFileSystem.cpp, app/src/main/cpp/skyline/services/fssrv/IFileSystem.h, app/src/main/cpp/skyline/services/nvdrv/INvDrvServices.h, app/src/main/cpp/skyline/services/nvdrv/devices/nvdevice.h, app/src/main/cpp/skyline/services/nvdrv/devices/nvhost_as_gpu.cpp, app/src/main/cpp/skyline/services/nvdrv/devices/nvhost_as_gpu.h, app/src/main/cpp/skyline/services/nvdrv/devices/nvhost_channel.cpp, app/src/main/cpp/skyline/services/nvdrv/devices/nvhost_channel.h, app/src/main/cpp/skyline/services/nvdrv/devices/nvhost_ctrl.cpp, app/src/main/cpp/skyline/services/nvdrv/devices/nvhost_ctrl_gpu.cpp, app/src/main/cpp/skyline/services/nvdrv/devices/nvhost_syncpoint.cpp, app/src/main/cpp/skyline/services/serviceman.cpp, app/src/main/cpp/skyline/vfs/directory.h, app/src/main/cpp/skyline/vfs/os_filesystem.cpp, app/src/main/cpp/skyline/vfs/os_filesystem.h, app/src/main/cpp/skyline/vfs/partition_filesystem.cpp, app/src/main/cpp/skyline/vfs/region_backing.h, app/src/main/cpp/skyline/vfs/rom_filesystem.cpp
IDirectory is used by many retail games to list the contents of directories, the NvServices functions added are all used by > 3.0.0 games.
=> Extend NvServices and implement IDirectory

app/src/main/cpp/skyline/gpu/gpfifo.cpp, app/src/main/cpp/skyline/gpu/gpfifo.h, app/src/main/cpp/skyline/gpu/memory_manager.cpp, app/src/main/cpp/skyline/gpu/memory_manager.h, app/src/main/cpp/skyline/services/nvdrv/INvDrvServices.cpp, app/src/main/cpp/skyline/services/nvdrv/devices/nvhost_ctrl.cpp, app/src/main/cpp/skyline/services/nvdrv/devices/nvhost_ctrl.h
See the individual commits for descriptions.
Please rebase and merge.
=> Implement various GPU and nvdrv fixes and optimisations

app/CMakeLists.txt, app/src/main/cpp/skyline/common/uuid.cpp, app/src/main/cpp/skyline/common/uuid.h, app/src/main/cpp/skyline/kernel/scheduler.cpp, app/src/main/cpp/skyline/kernel/types/KProcess.cpp, app/src/main/cpp/skyline/kernel/types/KThread.cpp, app/src/main/cpp/skyline/loader/nso.cpp, app/src/main/cpp/skyline/nce.cpp, app/src/main/cpp/skyline/services/am/controller/IApplicationFunctions.cpp, app/src/main/cpp/skyline/services/am/controller/IApplicationFunctions.h, app/src/main/cpp/skyline/services/am/controller/ISelfController.cpp, app/src/main/cpp/skyline/services/am/controller/ISelfController.h, app/src/main/cpp/skyline/services/mmnv/IRequest.cpp, app/src/main/cpp/skyline/services/mmnv/IRequest.h, app/src/main/cpp/skyline/services/nvdrv/devices/nvhost_channel.cpp, app/src/main/cpp/skyline/services/nvdrv/devices/nvhost_channel.h, app/src/main/cpp/skyline/services/pctl/IParentalControlService.cpp, app/src/main/cpp/skyline/services/pctl/IParentalControlService.h, app/src/main/cpp/skyline/services/pctl/IParentalControlServiceFactory.h, app/src/main/cpp/skyline/services/serviceman.cpp, app/src/main/cpp/skyline/vfs/nacp.h
Implements various service and kernel improvements that fix crashes in some games, most notably mmnv has been implemented, preventing a crash in SMO.
=> General service functionality improvements to enhance the user's experience

app/CMakeLists.txt, app/src/main/cpp/skyline/common.h, app/src/main/cpp/skyline/common/uuid.cpp, app/src/main/cpp/skyline/services/serviceman.cpp, app/src/main/cpp/skyline/services/spl/IRandomInterface.cpp, app/src/main/cpp/skyline/services/spl/IRandomInterface.h
See individual commits description.
=> csrng service implementation

app/CMakeLists.txt, app/src/main/cpp/skyline/services/glue/IContextRegistrar.h, app/src/main/cpp/skyline/services/glue/IWriterForSystem.cpp, app/src/main/cpp/skyline/services/glue/IWriterForSystem.h, app/src/main/cpp/skyline/services/serviceman.cpp
See commit description and linked issue.
=> Stub `ectx:w` and `ectx:aw` Glue services

app/src/main/cpp/skyline/common/utils.h, app/src/main/cpp/skyline/gpu.cpp, app/src/main/cpp/skyline/gpu/memory_manager.cpp, app/src/main/cpp/skyline/gpu/texture/texture.cpp, app/src/main/cpp/skyline/gpu/texture/texture.h, app/src/main/cpp/skyline/gpu/trait_manager.cpp, app/src/main/cpp/skyline/gpu/trait_manager.h
This is a bunch of minor things I noticed while trying to run Mario Odyssey.
=> Minor Vulkan fixes

app/src/main/java/emu/skyline/MainActivity.kt
Fixes an error exporting the logs.
=> Grant Uri permission when sharing logs

app/src/main/cpp/skyline/services/am/controller/ICommonStateGetter.cpp, app/src/main/cpp/skyline/services/am/controller/ICommonStateGetter.h, app/src/main/cpp/skyline/services/aocsrv/IAddOnContentManager.cpp, app/src/main/cpp/skyline/services/aocsrv/IAddOnContentManager.h, app/src/main/cpp/skyline/services/nfp/IUser.cpp, app/src/main/cpp/skyline/services/nfp/IUser.h
These services are called in a loop by **The Legend of Zelda: Breath of the Wild** if not implemented.
=> Stub `nfp` service + `ListAddonContent` + `IsVrModeEnabled `

app/CMakeLists.txt, app/src/main/cpp/skyline/input/npad_device.cpp, app/src/main/cpp/skyline/input/npad_device.h, app/src/main/cpp/skyline/input/sections/Npad.h, app/src/main/cpp/skyline/services/account/IAccountServiceForApplication.cpp, app/src/main/cpp/skyline/services/account/IAccountServiceForApplication.h, app/src/main/cpp/skyline/services/hid/IHidServer.cpp, app/src/main/cpp/skyline/services/hid/IHidServer.h, app/src/main/cpp/skyline/services/irs/IIrSensorServer.cpp, app/src/main/cpp/skyline/services/irs/IIrSensorServer.h, app/src/main/cpp/skyline/services/irs/iirsensor_core.h, app/src/main/cpp/skyline/services/serviceman.cpp
Those functions where required in order to boot DELTARUNE (is still not booting but the reason is not related to the services anymore)
- `StartSixAxisSensor`
- `GetVibrationDeviceInfo`
- `IsUserRegistrationRequestPermitted`
and the `IRS` service.
=> Create the IRS service and add other functions

app/CMakeLists.txt, app/src/main/cpp/skyline/applet/applet_creator.cpp, app/src/main/cpp/skyline/applet/applet_creator.h, app/src/main/cpp/skyline/kernel/ipc.h, app/src/main/cpp/skyline/services/am/applet/IApplet.cpp, app/src/main/cpp/skyline/services/am/applet/IApplet.h, app/src/main/cpp/skyline/services/am/applet/ILibraryAppletAccessor.cpp, app/src/main/cpp/skyline/services/am/applet/ILibraryAppletAccessor.h, app/src/main/cpp/skyline/services/am/controller/IApplicationFunctions.cpp, app/src/main/cpp/skyline/services/am/controller/ILibraryAppletCreator.cpp, app/src/main/cpp/skyline/services/am/controller/ILibraryAppletCreator.h, app/src/main/cpp/skyline/services/am/storage/IStorage.cpp, app/src/main/cpp/skyline/services/am/storage/IStorage.h, app/src/main/cpp/skyline/services/am/storage/IStorageAccessor.cpp, app/src/main/cpp/skyline/services/am/storage/IStorageAccessor.h, app/src/main/cpp/skyline/services/am/storage/TransferMemoryIStorage.cpp, app/src/main/cpp/skyline/services/am/storage/TransferMemoryIStorage.h, app/src/main/cpp/skyline/services/am/storage/VectorIStorage.cpp, app/src/main/cpp/skyline/services/am/storage/VectorIStorage.h, app/src/main/cpp/skyline/services/applet/common_arguments.h, app/src/main/cpp/skyline/services/base_service.h
This removes a stub for an applet and implements several applet related service calls.
=> Infrastructure for applets to be implemented

app/CMakeLists.txt, app/src/main/cpp/skyline/services/bcat/IBcatService.cpp, app/src/main/cpp/skyline/services/bcat/IBcatService.h, app/src/main/cpp/skyline/services/bcat/IServiceCreator.cpp, app/src/main/cpp/skyline/services/bcat/IServiceCreator.h, app/src/main/cpp/skyline/services/serviceman.cpp
Enough of bcat to get Kirby and the Forgotten Land booting (aside from ReadCbufValue)
=> Basic bcat:u implementation

app/CMakeLists.txt, app/src/main/cpp/skyline/services/bt/IBluetoothUser.cpp, app/src/main/cpp/skyline/services/bt/IBluetoothUser.h, app/src/main/cpp/skyline/services/btm/IBtmUser.cpp, app/src/main/cpp/skyline/services/btm/IBtmUser.h, app/src/main/cpp/skyline/services/btm/IBtmUserCore.cpp, app/src/main/cpp/skyline/services/btm/IBtmUserCore.h, app/src/main/cpp/skyline/services/serviceman.cpp
Pokémon Let's GO Pikachu and Eevee should get in-game now with a preexisting save file
=> Implement stub bt and btm:u

app/src/main/cpp/skyline/input/sections/TouchScreen.h, app/src/main/cpp/skyline/input/touch.cpp, app/src/main/cpp/skyline/input/touch.h, app/src/main/java/emu/skyline/EmulationActivity.kt
Adds missing parameter TouchAttribute  and emulates correctly the touch point index. Both changes are necessary on Voez to keep track of each finger.
=> Add HID touch attributes and touch index

app/src/main/AndroidManifest.xml, app/src/main/java/emu/skyline/SkylineApplication.kt, app/src/main/java/emu/skyline/provider/DocumentsProvider.kt
I'm not used to kotlin so a lot of the code is very messy but it works. I can try to fix anything you may have complaints about again sorry about code quality. Seems to work fine though for all the basic things (reading files, creating files, creating folders, moving items, copying items, etc)
=> Add DocumentProvider for accessing Skyline's files

BUILDING.md
changed First time user to First-time user
Fixes #1728
=> Fixed grammatical errors in BUILDING.md

app/src/main/cpp/loader_jni.cpp, app/src/main/cpp/skyline/vfs/nacp.cpp, app/src/main/cpp/skyline/vfs/nacp.h, app/src/main/java/emu/skyline/AppDialog.kt, app/src/main/java/emu/skyline/adapter/AppViewItem.kt, app/src/main/java/emu/skyline/data/DataItem.kt, app/src/main/java/emu/skyline/loader/RomFile.kt, app/src/main/res/layout/app_dialog.xml, app/src/main/res/layout/app_item_grid.xml, app/src/main/res/layout/app_item_grid_compact.xml, app/src/main/res/layout/app_item_linear.xml
I have added version of rom infos inside:
<details> 
<summary>App dialog</summary>
</details>
<details> 
<summary>App Item Grid</summary>
</details>
<details> 
<summary>App Item Grid Compact</summary>
</details>
<details> 
<summary>App Item List</summary>
</details>
I'm not really sure if it is usefull to add it for app items, maybe adding it to the dialog could be good enough feel free to tell me :)
Note: This is the first time ever i've touched to cpp files, i've partially understand how it was working and made change to make it work, feel free to tell me if i made any mistake
Note 2: I've seen that there is a lot of informations that could be helpfull to users like `Time player`, `Last Time Played`, `File Size` and other that i'd like to add if you think there is an interest
=> Add version infos about rom

app/src/main/cpp/loader_jni.cpp, app/src/main/cpp/skyline/vfs/nacp.cpp, app/src/main/cpp/skyline/vfs/nacp.h, app/src/main/java/emu/skyline/AppDialog.kt, app/src/main/java/emu/skyline/adapter/AppViewItem.kt, app/src/main/java/emu/skyline/adapter/controller/ControllerCheckBoxViewItem.kt, app/src/main/java/emu/skyline/adapter/controller/ControllerViewItem.kt, app/src/main/java/emu/skyline/data/DataItem.kt, app/src/main/java/emu/skyline/loader/RomFile.kt, app/src/main/res/layout/app_dialog.xml, app/src/main/res/layout/app_item_grid.xml, app/src/main/res/layout/app_item_grid_compact.xml, app/src/main/res/layout/app_item_linear.xml, app/src/main/res/layout/controller_checkbox_item.xml, app/src/main/res/layout/controller_item.xml
Not fond of claiming ownership of what is fundamentally just moving code around, but the appearance of the current layout where the version number is appended to the bottom looks awkward. This moves the version number between the title and the developer / distributor, which is the typical layout of individual package information.
=> Follow typical per-file detail formatting

app/src/main/cpp/skyline/input/npad.cpp, app/src/main/cpp/skyline/input/npad.h
fixes https://github.com/skyline-emu/skyline/issues/1928
=> fix supportedIds weird behavior in some games

app/CMakeLists.txt, app/src/main/cpp/skyline/services/bcat/IDeliveryCacheStorageService.cpp, app/src/main/cpp/skyline/services/bcat/IDeliveryCacheStorageService.h, app/src/main/cpp/skyline/services/bcat/IServiceCreator.cpp, app/src/main/cpp/skyline/services/bcat/IServiceCreator.h
Simple stub for the service. Allows "groove coaster wai wai party" to boot.
=> service: bcat: Stub CreateDeliveryCacheStorageService

app/src/main/cpp/skyline/kernel/types/KProcess.cpp
Since InsertThread can block for paused threads, we need to ensure we unlock syncWaiterMutex when calling it.
=> Restructure ConditionalVariableSignal to avoid potential deadlock

app/CMakeLists.txt, app/src/main/cpp/skyline/applet/applet_creator.cpp, app/src/main/cpp/skyline/applet/web_applet.cpp, app/src/main/cpp/skyline/applet/web_applet.h
=> Stub the web applet

app/CMakeLists.txt, app/src/main/cpp/skyline/common/utils.h, app/src/main/cpp/skyline/loader/nro.h, app/src/main/cpp/skyline/services/ro/IRoInterface.cpp, app/src/main/cpp/skyline/services/ro/IRoInterface.h, app/src/main/cpp/skyline/services/serviceman.cpp
This is slightly hacky but for now we can't particularly make it much cleaner without rewriting memory infra.
=> Partially implement ldr:ro

app/CMakeLists.txt, app/src/main/cpp/skyline/services/serviceman.cpp, app/src/main/cpp/skyline/services/socket/bsd/IClient.cpp, app/src/main/cpp/skyline/services/socket/bsd/IClient.h, app/src/main/cpp/skyline/services/socket/nsd/IManager.cpp, app/src/main/cpp/skyline/services/socket/nsd/IManager.h, app/src/main/cpp/skyline/services/socket/sfdnsres/IResolver.cpp, app/src/main/cpp/skyline/services/socket/sfdnsres/IResolver.h
Required by some games to boot (e.g. No Man's Sky)
=> Stub nsd:u/nsd:a and sfdnsres services. Stub some bsd functions

app/src/main/cpp/emu_jni.cpp, app/src/main/java/emu/skyline/EmulationActivity.kt, app/src/main/java/emu/skyline/input/HostEvent.kt, app/src/main/java/emu/skyline/input/InputHandler.kt, app/src/main/java/emu/skyline/input/dialog/ButtonDialog.kt
See individual commit description.
=> Kotlin input code cleanup + controller input fixes

app/CMakeLists.txt, app/src/main/cpp/skyline/services/capsrv/IAlbumAccessorService.cpp, app/src/main/cpp/skyline/services/capsrv/IAlbumAccessorService.h, app/src/main/cpp/skyline/services/capsrv/IAlbumApplicationService.cpp, app/src/main/cpp/skyline/services/capsrv/IAlbumApplicationService.h, app/src/main/cpp/skyline/services/capsrv/ICaptureControllerService.cpp, app/src/main/cpp/skyline/services/capsrv/ICaptureControllerService.h, app/src/main/cpp/skyline/services/capsrv/IScreenShotApplicationService.cpp, app/src/main/cpp/skyline/services/capsrv/IScreenShotApplicationService.h, app/src/main/cpp/skyline/services/serviceman.cpp
Some games are not booting without it (e.g Monster Hunter: Rise, Super Smash Bros. Ultimate and etc.)
=> Stub capsrv services (caps:a, caps:c, caps:u, caps:su)

app/src/main/java/emu/skyline/KeyReader.kt, app/src/main/java/emu/skyline/MainActivity.kt, app/src/main/java/emu/skyline/SettingsActivity.kt, app/src/main/java/emu/skyline/input/ControllerActivity.kt, app/src/main/java/emu/skyline/preference/GpuDriverActivity.kt, app/src/main/java/emu/skyline/preference/KeyPickerPreference.kt, app/src/main/java/emu/skyline/utils/GpuDriverHelper.kt, app/src/main/java/emu/skyline/utils/WindowInsetsHelper.kt, app/src/main/java/emu/skyline/utils/ZipUtils.kt, app/src/main/res/layout/gpu_driver_activity.xml, app/src/main/res/values/strings.xml
* Close the input and output file streams before moving the output file to the final destination
* Clean up the destination path before moving the new file
* Introduce a `ImportResult` return value to differentiate between the possible causes of import errors
* Display more meaningful error messages in the UI
=> Improve robustness of `KeyReader.import`

app/src/main/cpp/skyline/audio.cpp, app/src/main/cpp/skyline/audio.h, app/src/main/cpp/skyline/common/android_settings.h, app/src/main/cpp/skyline/common/settings.h, app/src/main/cpp/skyline/services/audio/IAudioRenderer/IAudioRenderer.cpp, app/src/main/java/emu/skyline/utils/NativeSettings.kt, app/src/main/java/emu/skyline/utils/PreferenceSettings.kt, app/src/main/res/values/strings.xml, app/src/main/res/xml/preferences.xml
Might fix some games (e.g The Legend of Zelda: Skyward Sword HD)
=> Add possibility to disable audio output

app/src/main/cpp/loader_jni.cpp, app/src/main/cpp/skyline/os.cpp, app/src/main/cpp/skyline/vfs/nacp.cpp, app/src/main/cpp/skyline/vfs/nacp.h, app/src/main/java/emu/skyline/AppDialog.kt, app/src/main/java/emu/skyline/data/DataItem.kt, app/src/main/java/emu/skyline/loader/RomFile.kt, app/src/main/res/layout/app_dialog.xml, app/src/main/res/values/strings.xml
Also if you hold with touch the Title ID it will copy it to clipboard
=> Add TitleId TextView in App Dialog

app/src/main/cpp/skyline/services/account/IAccountServiceForApplication.cpp, app/src/main/cpp/skyline/services/account/IAccountServiceForApplication.h, app/src/main/cpp/skyline/services/account/IManagerForApplication.cpp, app/src/main/cpp/skyline/services/account/IManagerForApplication.h, app/src/main/cpp/skyline/services/audio/IAudioDevice.cpp, app/src/main/cpp/skyline/services/audio/IAudioDevice.h, app/src/main/cpp/skyline/services/nifm/IRequest.cpp, app/src/main/cpp/skyline/services/nifm/IRequest.h, app/src/main/cpp/skyline/services/prepo/IPrepoService.cpp, app/src/main/cpp/skyline/services/prepo/IPrepoService.h
Should fix crashes in some games (KLONOA, Splatoon 3, Bayonetta 3 and etc. (they won't boot, but fixes are for the future))
=> Some stub/fixes for some new games

app/src/main/cpp/skyline/kernel/scheduler.cpp, app/src/main/cpp/skyline/kernel/scheduler.h, app/src/main/cpp/skyline/kernel/svc.cpp, app/src/main/cpp/skyline/kernel/types/KProcess.cpp, app/src/main/cpp/skyline/kernel/types/KProcess.h, app/src/main/cpp/skyline/kernel/types/KThread.h, app/src/main/cpp/skyline/loader/loader.cpp, app/src/main/cpp/skyline/nce.cpp
This PR is a result of months of research into crashes and freezes on titles such as ARMS, BOTW, etc. A major class of scheduling bugs has been fixed which should affect a lot of games but there may be side effects due to the number of changes and regressions are expected.
=> Fix Synchronization Primitive Bugs

app/src/main/java/emu/skyline/preference/ProfilePicturePreference.kt
Realized I had no idea how the picture looked after selecting it, so I used the existing preference icon as a preview. 
Also adds a recycle of the bitmap after storing it to free up the resources, since bitmaps tend to be expensive left around.
=> Display a preview of the current profile picture

app/src/main/cpp/emu_jni.cpp, app/src/main/cpp/skyline/input/npad_device.cpp, app/src/main/cpp/skyline/input/npad_device.h, app/src/main/cpp/skyline/input/sections/Npad.h, app/src/main/java/emu/skyline/EmulationActivity.kt, app/src/main/java/emu/skyline/input/InputHandler.kt
This ports the motion implementation of yuzu. It will work as long as the device has at least gyro or accelerometer. You need both sensors to have accurate measurements.
=> Implement SixAxis sensor

app/src/main/cpp/skyline/services/fssrv/IFileSystem.cpp, app/src/main/cpp/skyline/services/fssrv/IFileSystem.h
solves the problem that you can't save in some games.
I am still trying to figure out how to implement it correctly
=> quick and dirty implementation for GetFreeSpaceSize

app/src/main/cpp/skyline/kernel/svc.cpp
Reduces memory usage buildup over time, may affect performance.
=> Deallocate Unmapped memory pages

app/src/main/cpp/skyline/gpu/interconnect/common/textures.cpp, app/src/main/cpp/skyline/gpu/texture/format.h
These were the opposite to what they should have been.
=> Fix depth-stencil formats

app/src/main/java/emu/skyline/AppDialog.kt, app/src/main/java/emu/skyline/MainActivity.kt, app/src/main/java/emu/skyline/adapter/AppViewItem.kt, app/src/main/java/emu/skyline/data/DataItem.kt
`... and one condition to find them without the need for multiple instances and passing a condition. The data class can simply return the same instance every time it's necessary.`
Jokes aside, there are a minimum of 3 instances of the missingIcon Bitmap per run and it's a static icon. If the explanation isn't convincing enough, compare the load times.
=> One missing Bitmap to rule them all

app/src/main/java/emu/skyline/data/DataItem.kt, app/src/main/java/emu/skyline/input/Controller.kt, app/src/main/java/emu/skyline/input/ControllerActivity.kt, app/src/main/java/emu/skyline/input/InputHandler.kt
I'm not 100% sold on the string concatenation, despite Android Studio being all about it. It seems off because it would actually print "null" unless there is something there in place of it.
=> Clear or suppress some easy lint warnings

app/src/main/java/emu/skyline/MainActivity.kt, app/src/main/java/emu/skyline/MainViewModel.kt
Refering to https://github.com/skyline-emu/skyline/pull/2253 and Closes https://github.com/skyline-emu/skyline/issues/2015
=> Add automatic refreshing games list

app/src/main/cpp/skyline/vfs/os_filesystem.cpp, app/src/main/java/emu/skyline/AppDialog.kt, app/src/main/res/layout/app_dialog.xml, app/src/main/res/values/strings.xml
=> Import/Export Game Saves
